### PR TITLE
[FE] use chroma.js to generate diffrent light colors for team members results view

### PR DESCRIPTION
**Pull request by shirve**
### Changes
- Improved `getRandomLightColor` utility logic to use `chroma.js` library
- Changed logic not to generate color similar to team icon color

### CODE REVIEW

**Comment by tobob** [comment]
@shirve it looks good, but can we wait for https://github.com/Selleo/team-fingerprints/pull/471 to be merged and then apply chroma logic into color generation for team members?

**Review by tobob — CHANGES_REQUESTED** [review]
we want to include this into team member generation

**Comment by tobob** [comment]
@shirve related ticket was merged, so you can adjust the implementation, also can you make sure that for example, chroma won't generate the same color as a team is, to resolve problems such as:
image (10)


when team color and color generated for user are almost the same?

**Review by tobob — APPROVED** [review]

**Comment by tobob** [comment]
@shirve can we implement it in a matter where this light color will be aways the same based on user's email?

**Comment by Matesty** [comment]
- We would rather avoid such a situation that team members have the same color

Zrzut ekranu 2022-11-25 100611

**Review by tobob — APPROVED** [review]

**Comment by tobob** [comment]
@Matesty you can check it again ;)

**Review by Matesty — APPROVED** [review]

**Pull request merged**
