### PR TITLE
[FE] maintenance eslint

### PR DESCRIPTION
**Pull request by typeWolffo**
### Changes

Fixed eslint errors - mostly shadow variable names, usage of variables before initialization, imports and missing return from 
functions.

### CODE REVIEW

**Comment by typeWolffo** [comment]
@Matesty there are a lot of small changes here that I am not 100% sure about. Could you please test the whole application?

**Review by tobob — APPROVED** [review]

**Comment by tobob** [comment]
@Matesty please check this PR very deeply

**Comment by Matesty** [comment]
Good job!💪@typeWolffo only one thing that does not work I noticed:
 
- filters are not displayed

image

- login in/out works
- completing the survey works
- creating/editing the survey works
- inviting to company/team works
- emails works
- creating/editing company/team works
- completing the survey works
- breadcrumbs works
- sorting by category works
- back button works
- editing profile works
- admin panel works
- leaving company works
- adding/deleting new filters works
- global results works
- redirects works

**Comment by tobob** [comment]
@typeWolffo can you prioritize this?

**Review by Matesty — APPROVED** [review]

**Pull request merged**
