### PR TITLE
F/E if user does not have any company and role assigned then compare his/her result with all

### PR DESCRIPTION
**Pull request by shirve**
### Changes
- Added new hexagon shape in `ColoredShape` and `Chart` component
- Displaying comparison with global survey results if user doesn't belong to any company or team

### Preview
- Survey results view for user **with** companies
Screenshot 2022-11-15 at 11 54 08
- Survey results view for user **without** companies
Screenshot 2022-11-15 at 11 54 51

### CODE REVIEW

**Review by typeWolffo — APPROVED** [review]

**Comment by tobob** [comment]
@shirve adding new shape was not a part of this ticket, making a decision in this area need to be consulted with me or @Dariusz-Wylon

**Comment by tobob** [comment]
> > @shirve adding new shape was not a part of this ticket, making a decision in this area need to be consulted with me or @Dariusz-Wylon
> 
> There was a new shape in the issue preview of how it was supposed to look like hence why I added it. Which shape of the existing ones do you want me to use here instead?

wait, maybe we will stay with your approach ;)

**Comment by tobob** [comment]
@shirve sorry, also my bad, that I left this icon in a preview image, I should be more precise 😔

**Review by tobob — COMMENTED** [review]
overall looks good, so we will wait for @Dariusz-Wylon to make a decision

**Comment by tobob** [comment]
@Dariusz-Wylon gives us his blessing

**Pull request merged**
