### PR TITLE
Trimming string inputs in DTO's

### PR DESCRIPTION
**Pull request by yetiasg**

### CODE REVIEW

**Review by polakowski — CHANGES_REQUESTED** [review]
Try to avoid repetitions :)

image

**Comment by tobob** [comment]
> Try to avoid repetitions :)
> 
> image

@yetiasg you can create custom decorator `@Trim`

**Comment by tobob** [comment]
@yetiasg something is odd with this PR, can you create a fresh branch and cherry-pick your commits?

**Review by polakowski — APPROVED** [review]
I'm happy with merging this PR, as soon as unwanted commits are removed :rocket:

**Comment by tobob** [comment]
@polakowski merged by another PR

**Pull request closed without merging**
